// File generated by flutterfire_cli.
// This file configures Firebase for your Flutter application.

import 'dart:io';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_example_key_hello_25aab_web_key',
    appId: '1:1234567890:web:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'hello-25aab',
    authDomain: 'hello-25aab.firebaseapp.com',
    storageBucket: 'hello-25aab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_example_key_hello_25aab_android_key',
    appId: '1:1234567890:android:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'hello-25aab',
    storageBucket: 'hello-25aab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_example_key_hello_25aab_ios_key',
    appId: '1:1234567890:ios:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'hello-25aab',
    storageBucket: 'hello-25aab.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_example_key_hello_25aab_macos_key',
    appId: '1:1234567890:macos:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'hello-25aab',
    storageBucket: 'hello-25aab.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_example_key_hello_25aab_windows_key',
    appId: '1:1234567890:windows:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'hello-25aab',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyD_example_key_hello_25aab_linux_key',
    appId: '1:1234567890:linux:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'hello-25aab',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions.currentPlatform is not supported for this target platform.',
        );
    }
  }
}

// Fallback for non-Flutter environments
const bool kIsWeb = false;

enum TargetPlatform {
  android,
  iOS,
  macOS,
  windows,
  linux,
  web,
}

TargetPlatform get defaultTargetPlatform {
  if (Platform.isAndroid) {
    return TargetPlatform.android;
  } else if (Platform.isIOS) {
    return TargetPlatform.iOS;
  } else if (Platform.isMacOS) {
    return TargetPlatform.macOS;
  } else if (Platform.isWindows) {
    return TargetPlatform.windows;
  } else if (Platform.isLinux) {
    return TargetPlatform.linux;
  }
  return TargetPlatform.android;
}
